spring:
  application:
    name: fuss
server:
    port: 8081

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
    info:
      show-details: always
